spring:
  application:
    name: cs-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/heliangren/cloud_config.git
          username: heliangren
          password: kirt_7421
server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      #defaultZone: http://${helr.name}:${helr.password}@localhost:8761/eureka/

#helr:
#  name: helr
#  password: 123456
